export const payrollListMock: PayrollListItemData[] = [
    {
        employeeId: 1,
        employeeName: "이민준",
        employmentType: "REGULAR",
        payrollId: 101,
        preparationStatus: "CONFIRMED",
        totalEarnings: 3670000,
        totalDeductions: 408580,
        netPay: 3261420,
        revisionNo: 1,
    },
    {
        employeeId: 2,
        employeeName: "한소율",
        employmentType: "REGULAR",
        payrollId: 102,
        preparationStatus: "CONFIRMED",
        totalEarnings: 4000000,
        totalDeductions: 501000,
        netPay: 3499000,
        revisionNo: 2,
    },
    {
        employeeId: 3,
        employeeName: "윤재하",
        employmentType: "FIXED_TERM",
        payrollId: 103,
        preparationStatus: "CONFIRMED",
        totalEarnings: 3100000,
        totalDeductions: 380580,
        netPay: 2719420,
        revisionNo: 1,
    },
    {
        employeeId: 4,
        employeeName: "김서연",
        employmentType: "REGULAR",
        payrollId: 104,
        preparationStatus: "CALCULATED",
        totalEarnings: 3200000,
        totalDeductions: 380120,
        netPay: 2819880,
        revisionNo: 1,
    },
    {
        employeeId: 5,
        employeeName: "박도윤",
        employmentType: "FIXED_TERM",
        payrollId: 105,
        preparationStatus: "CALCULATED",
        totalEarnings: 1342000,
        totalDeductions: 146000,
        netPay: 1196000,
        revisionNo: 1,
    },
    {
        employeeId: 6,
        employeeName: "최지우",
        employmentType: "PART_TIME",
        payrollId: 106,
        preparationStatus: "DRAFT",
        totalEarnings: null,
        totalDeductions: null,
        netPay: null,
        revisionNo: 1,
    },
    {
        employeeId: 7,
        employeeName: "정하람",
        employmentType: "PART_TIME",
        payrollId: null,
        preparationStatus: "NOT_CREATED",
        totalEarnings: null,
        totalDeductions: null,
        netPay: null,
        revisionNo: 0,
    },
    {
        employeeId: 8,
        employeeName: "오세훈",
        employmentType: null,
        payrollId: null,
        preparationStatus: "NOT_CREATED",
        totalEarnings: null,
        totalDeductions: null,
        netPay: null,
        revisionNo: 0,
    },
];
