export const payrollDetailMock: Record<number, PayrollDetailData> = {
    101: {
        payrollId: 101,
        employeeName: "이민준",
        employmentType: "REGULAR",
        preparationStatus: "CONFIRMED",
        yearMonth: "2026-08",
        scheduledPayDate: "2026-09-05",
        revisionNo: 1,
        memo: "확인 완료",
        attendance: {
            workDays: 21,
            workHours: 168,
            overtimeHours: 6,
            nightHours: 2,
            holidayHours: 0,
            paidLeaveHours: 8,
        },
        contract: {
            employmentTypeLabel: "정규직",
            salaryTypeLabel: "월급제",
            baseSalary: 3200000,
            ordinaryHourlyWage: 20000,
            weeklyContractHours: 40,
        },
        earnings: [
            { name: "기본급", amount: 3200000, editable: false },
            { name: "식대", amount: 200000, editable: false },
            {
                name: "연장근로수당",
                amount: 170000,
                editable: false,
                originalAmount: 180000,
                adjusted: true,
                adjustmentReason: "근태 정정사항 수기 반영",
                calculationFormula: "20,000원 × 6시간 × 1.5",
                calculationBasis: "rate: 1.5 · hours: 6 · ordinaryWage: 20000",
            },
            { name: "특별수당", amount: 100000, editable: true },
        ],
        deductions: [
            { name: "국민연금", amount: 152000, editable: false },
            { name: "건강보험", amount: 115000, editable: false },
            { name: "장기요양보험", amount: 15000, editable: false },
            { name: "고용보험", amount: 30000, editable: false },
            { name: "소득세", amount: 87800, editable: false },
            { name: "지방소득세", amount: 8780, editable: false },
        ],
        totalEarnings: 3670000,
        totalDeductions: 408580,
        netPay: 3261420,
        statement: {
            status: "READY",
            generatedAt: "2026.08.12 14:25",
            fileSizeLabel: "178KB",
        },
    },
    102: {
        payrollId: 102,
        employeeName: "한소율",
        employmentType: "REGULAR",
        preparationStatus: "CONFIRMED",
        yearMonth: "2026-08",
        scheduledPayDate: "2026-09-05",
        revisionNo: 2,
        memo: null,
        attendance: {
            workDays: 22,
            workHours: 176,
            overtimeHours: 10,
            nightHours: 0,
            holidayHours: 0,
            paidLeaveHours: 0,
        },
        contract: {
            employmentTypeLabel: "정규직",
            salaryTypeLabel: "월급제",
            baseSalary: 3700000,
            ordinaryHourlyWage: 22000,
            weeklyContractHours: 40,
        },
        earnings: [
            { name: "기본급", amount: 3700000, editable: false },
            { name: "연장근로수당", amount: 300000, editable: false },
        ],
        deductions: [
            { name: "국민연금", amount: 186000, editable: false },
            { name: "건강보험", amount: 140000, editable: false },
            { name: "장기요양보험", amount: 18000, editable: false },
            { name: "고용보험", amount: 37000, editable: false },
            { name: "소득세", amount: 107000, editable: false },
            { name: "지방소득세", amount: 13000, editable: false },
        ],
        totalEarnings: 4000000,
        totalDeductions: 501000,
        netPay: 3499000,
        statement: {
            status: "READY",
            generatedAt: "2026.08.13 09:10",
            fileSizeLabel: "181KB",
        },
    },
    103: {
        payrollId: 103,
        employeeName: "윤재하",
        employmentType: "FIXED_TERM",
        preparationStatus: "CONFIRMED",
        yearMonth: "2026-08",
        scheduledPayDate: "2026-09-05",
        revisionNo: 1,
        memo: null,
        attendance: {
            workDays: 20,
            workHours: 160,
            overtimeHours: 5,
            nightHours: 0,
            holidayHours: 0,
            paidLeaveHours: 0,
        },
        contract: {
            employmentTypeLabel: "기간제",
            salaryTypeLabel: "월급제",
            baseSalary: 2900000,
            ordinaryHourlyWage: 18000,
            weeklyContractHours: 40,
        },
        earnings: [
            { name: "기본급", amount: 2900000, editable: false },
            { name: "연장근로수당", amount: 200000, editable: false },
        ],
        deductions: [
            { name: "국민연금", amount: 144000, editable: false },
            { name: "건강보험", amount: 108000, editable: false },
            { name: "장기요양보험", amount: 14000, editable: false },
            { name: "고용보험", amount: 28000, editable: false },
            { name: "소득세", amount: 78000, editable: false },
            { name: "지방소득세", amount: 8580, editable: false },
        ],
        totalEarnings: 3100000,
        totalDeductions: 380580,
        netPay: 2719420,
        statement: {
            status: "FAILED",
            generatedAt: null,
            fileSizeLabel: null,
            failureReason: "PDF 렌더링 서버 응답 지연으로 명세서 생성에 실패했습니다.",
        },
    },
    104: {
        payrollId: 104,
        employeeName: "김서연",
        employmentType: "REGULAR",
        preparationStatus: "CALCULATED",
        yearMonth: "2026-08",
        scheduledPayDate: "2026-09-05",
        revisionNo: 1,
        memo: null,
        attendance: {
            workDays: 21,
            workHours: 168,
            overtimeHours: 5,
            nightHours: 0,
            holidayHours: 0,
            paidLeaveHours: 0,
        },
        contract: {
            employmentTypeLabel: "정규직",
            salaryTypeLabel: "월급제",
            baseSalary: 3000000,
            ordinaryHourlyWage: 19000,
            weeklyContractHours: 40,
        },
        earnings: [
            { name: "기본급", amount: 3000000, editable: false },
            { name: "연장근로수당", amount: 200000, editable: false },
        ],
        deductions: [
            { name: "국민연금", amount: 144000, editable: false },
            { name: "건강보험", amount: 108000, editable: false },
            { name: "장기요양보험", amount: 14000, editable: false },
            { name: "고용보험", amount: 28000, editable: false },
            { name: "소득세", amount: 78000, editable: false },
            { name: "지방소득세", amount: 8120, editable: false },
        ],
        totalEarnings: 3200000,
        totalDeductions: 380120,
        netPay: 2819880,
        statement: null,
    },
    105: {
        payrollId: 105,
        employeeName: "박도윤",
        employmentType: "FIXED_TERM",
        preparationStatus: "CALCULATED",
        yearMonth: "2026-08",
        scheduledPayDate: "2026-09-05",
        revisionNo: 1,
        memo: null,
        attendance: {
            workDays: 12,
            workHours: 96,
            overtimeHours: 0,
            nightHours: 0,
            holidayHours: 0,
            paidLeaveHours: 0,
        },
        contract: {
            employmentTypeLabel: "기간제",
            salaryTypeLabel: "월급제",
            baseSalary: 1200000,
            ordinaryHourlyWage: 12500,
            weeklyContractHours: 24,
        },
        earnings: [
            { name: "기본급", amount: 1200000, editable: false },
            { name: "연장근로수당", amount: 142000, editable: false },
        ],
        deductions: [
            { name: "국민연금", amount: 62000, editable: false },
            { name: "건강보험", amount: 46000, editable: false },
            { name: "장기요양보험", amount: 6000, editable: false },
            { name: "고용보험", amount: 12000, editable: false },
            { name: "소득세", amount: 18000, editable: false },
            { name: "지방소득세", amount: 2000, editable: false },
        ],
        totalEarnings: 1342000,
        totalDeductions: 146000,
        netPay: 1196000,
        statement: null,
    },
};

export const payrollRevisionHistoryMock: Record<number, PayrollRevisionSummary[]> = {
    102: [
        {
            payrollId: 102,
            revisionNo: 2,
            isLatest: true,
            preparationStatus: "CONFIRMED",
            totalEarnings: 4000000,
            totalDeductions: 501000,
            netPay: 3499000,
            confirmedAt: "2026.08.13 09:10",
        },
        {
            payrollId: 90,
            revisionNo: 1,
            isLatest: false,
            preparationStatus: "CONFIRMED",
            totalEarnings: 3900000,
            totalDeductions: 486000,
            netPay: 3414000,
            confirmedAt: "2026.08.12 10:00",
        },
    ],
};
