export const LECTURES = [
    {
        title: "고1 수학 정규반",
        subject: "수학",
        semester: "2026 여름학기",
        type: "정규반",
        grade: "고1",
        teacher: "김선생",
        classroom: "A101",
        schedules: ["월 19:00~21:00"],
        fee: "300,000원",
        feeType: "월정액",
        studentCount: 8,
    },
    {
        title: "고3 수학 특강",
        subject: "수학",
        semester: "2026 여름학기",
        type: "특강",
        grade: "고3",
        teacher: "이선생",
        classroom: "B201",
        schedules: ["화 10:00~12:00", "목 10:00~12:00"],
        fee: "50,000원",
        feeType: "회당",
        studentCount: 12,
    },
    {
        title: "고2 영어 정규반",
        subject: "영어",
        semester: "2026 여름학기",
        type: "정규반",
        grade: "고2",
        teacher: "박선생",
        classroom: "A102",
        schedules: ["수 15:00~17:00"],
        fee: "280,000원",
        feeType: "월정액",
        studentCount: 6,
    },
    {
        title: "중3 국어 클리닉",
        subject: "국어",
        semester: "2026 여름학기",
        type: "클리닉",
        grade: "중3",
        teacher: "정선생",
        classroom: "C301",
        schedules: ["금 14:00~16:00"],
        fee: "40,000원",
        feeType: "회당",
        studentCount: 4,
    },
    {
        title: "고1 과학 정규반",
        subject: "과학",
        semester: "2026 여름학기",
        type: "정규반",
        grade: "고1",
        teacher: "오선생",
        classroom: "B202",
        schedules: ["토 09:00~11:00"],
        fee: "260,000원",
        feeType: "월정액",
        studentCount: 10,
    },
] as const;
