import { MEMO_COLORS, type MemoColor } from "@/feature/memo/components/MemoColorPicker";

// 임시로 사용할 타입입니다. 추후 API 연동을 진행하면서 삭제할 예정입니다.
export type ScheduleEvent = {
  id: number;
  title: string;
  date: Date;
  allDay: boolean;
  startTime?: string; // "HH:mm" (24시간), allDay가 아닐 때만 사용
  endTime?: string;
  color: MemoColor;
  content: string;
  createdAt: string; // "yyyy.MM.dd"
};

// 임시로 사용할 더미데이터 입니다. 추후 API 연동을 진행하면서 삭제할 예정입니다.
export const scheduleEvents: ScheduleEvent[] = [
  {
    id: 1,
    title: "2학기 수업 준비 회의",
    date: new Date(2026, 7, 3),
    allDay: false,
    startTime: "10:00",
    endTime: "11:30",
    color: MEMO_COLORS[2],
    content: "2학기 수업 계획 논의 및 교재 배분",
    createdAt: "2026.08.01",
  },
  {
    id: 2,
    title: "원생 출석 점검",
    date: new Date(2026, 7, 3),
    allDay: false,
    startTime: "09:00",
    endTime: "09:30",
    color: MEMO_COLORS[1],
    content: "전 반 출석 현황 점검 및 미출석자 학부모 연락",
    createdAt: "2026.08.01",
  },
  {
    id: 3,
    title: "월간 수납 현황 보고",
    date: new Date(2026, 7, 10),
    allDay: false,
    startTime: "14:00",
    endTime: "15:00",
    color: MEMO_COLORS[10],
    content: "8월 수납 현황 정리 및 미납자 안내",
    createdAt: "2026.08.05",
  },
  {
    id: 4,
    title: "광복절",
    date: new Date(2026, 7, 15),
    allDay: true,
    color: MEMO_COLORS[0],
    content: "공휴일",
    createdAt: "2026.08.01",
  },
  {
    id: 5,
    title: "전체 교직원 회의",
    date: new Date(2026, 7, 17),
    allDay: false,
    startTime: "09:00",
    endTime: "10:00",
    color: MEMO_COLORS[11],
    content: "2학기 운영 계획 공유",
    createdAt: "2026.08.10"
  },
  {
    id: 6,
    title: "수학A반 모의고사",
    date: new Date(2026, 7, 18),
    allDay: false,
    startTime: "14:00",
    endTime: "16:00",
    color: MEMO_COLORS[2],
    content: "2학기 대비 모의고사 실시",
    createdAt: "2026.08.10",
  },
  {
    id: 7,
    title: "영어B반 단어시험",
    date: new Date(2026, 7, 18),
    allDay: false,
    startTime: "10:00",
    endTime: "11:00",
    color: MEMO_COLORS[1],
    content: "단원 5-6 단어 시험",
    createdAt: "2026.08.10",
  },
  {
    id: 8,
    title: "학부모 상담 주간 시작",
    date: new Date(2026, 7, 20),
    allDay: false,
    startTime: "13:00",
    endTime: "18:00",
    color: MEMO_COLORS[4],
    content: "2학기 상담 주간, 사전 예약자 순으로 진행",
    createdAt: "2026.08.12",
  },
  {
    id: 9,
    title: "직원 워크샵",
    date: new Date(2026, 7, 20),
    allDay: false,
    startTime: "09:00",
    endTime: "17:00",
    color: MEMO_COLORS[2],
    content: "전 직원 대상 2학기 운영 워크샵",
    createdAt: "2026.08.12",
  },
  {
    id: 10,
    title: "과학D반 실험수업",
    date: new Date(2026, 7, 20),
    allDay: false,
    startTime: "15:00",
    endTime: "17:00",
    color: MEMO_COLORS[8],
    content: "화학 반응 실험 수업",
    createdAt: "2026.08.12",
  },
  {
    id: 11,
    title: "국어C반 논술특강",
    date: new Date(2026, 7, 20),
    allDay: false,
    startTime: "19:00",
    endTime: "21:00",
    color: MEMO_COLORS[7],
    content: "논술 특강 3회차",
    createdAt: "2026.08.12",
  },
  {
    id: 12,
    title: "신규 강사 오리엔테이션",
    date: new Date(2026, 7, 21),
    allDay: false,
    startTime: "09:00",
    endTime: "12:00",
    color: MEMO_COLORS[5],
    content: "신규 강사 대상 학원 운영 방침 안내",
    createdAt: "2026.08.14",
  },
  {
    id: 13,
    title: "급여 지급일",
    date: new Date(2026, 7, 25),
    allDay: true,
    color: MEMO_COLORS[2],
    content: "8월 급여 지급",
    createdAt: "2026.08.01",
  },
  {
    id: 14,
    title: "개학식",
    date: new Date(2026, 7, 25),
    allDay: false,
    startTime: "10:00",
    endTime: "11:00",
    color: MEMO_COLORS[11],
    content: "2학기 개학식",
    createdAt: "2026.08.14",
  },
  {
    id: 15,
    title: "방학 종료",
    date: new Date(2026, 7, 31),
    allDay: true,
    color: MEMO_COLORS[0],
    content: "여름방학 종료",
    createdAt: "2026.08.01",
  },
];
